apiVersion: 1

datasources:
  - name: WMS Prometheus
    uid: wms-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: WMS Loki
    uid: wms-loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
