import type { FormEvent } from 'react';

export type Category = { id: string; name: string; parentId?: string | null };
export type Product = { id: string; sku: string; name: string; description?: string | null; unit: string; categoryId?: string | null; categoryName?: string | null; costPrice: number; barcode?: string | null; color?: string | null; size?: string | null; salePrice?: number; warehouseId?: string | null; locationId?: string | null; quantityImported?: number; supplierId?: string | null; importedAt?: string | null; note?: string | null; imageUrl?: string | null; createdAt: string };
export type ProductResponse = { data: Product[]; meta: { page: number; limit: number; total: number } };
export type User = { id?: string; email: string; fullName?: string; role: string; status?: string; createdAt?: string };
export type AuthResponse = { accessToken: string; user: User };
export type UploadProductImageResponse = { fileName: string; imageUrl: string };
export type Warehouse = { id: string; code: string; name: string; address?: string | null };
export type Location = { id: string; warehouseId: string; warehouseCode?: string; code: string; description?: string | null };
export type StockLevel = { id: string; productId: string; warehouseId: string; warehouseCode?: string; locationId?: string | null; locationCode?: string | null; quantity: number; reservedQuantity?: number; availableQuantity?: number; minQuantity: number; lastMovementAt?: string };
export type StockAlert = StockLevel;
export type Supplier = { id: string; code: string; name: string; contactName?: string | null; phone?: string | null; email?: string | null; address?: string | null };
export type Transaction = { id: string; type: 'INBOUND' | 'OUTBOUND'; code: string; warehouseId: string; supplierId?: string | null; status: string; totalQuantity: number; totalValue: number; createdAt: string; items: Array<{ id?: string; productId: string; locationId?: string | null; quantity: number; unitPrice: number }> };
export type ProductForm = { sku: string; name: string; description: string; unit: string; categoryId: string; costPrice: string; barcode?: string; color?: string; size?: string; salePrice?: string; warehouseId?: string; locationId?: string; quantityImported?: string; supplierId?: string; importedAt?: string; note?: string; imageUrl?: string };
export type WarehouseForm = { code: string; name: string; address: string };
export type CategoryForm = { name: string; parentId: string };
export type LocationForm = { code: string; description: string };
export type StockForm = { productId: string; warehouseId: string; locationId: string; quantity: string; minQuantity: string; reason: string };
export type TransferForm = { productId: string; fromWarehouseId: string; fromLocationId: string; toWarehouseId: string; toLocationId: string; quantity: string; reason: string };
export type SupplierForm = { code: string; name: string; contactName: string; phone: string; email: string; address: string };
export type PasswordForm = { oldPassword: string; newPassword: string };
export type TransactionForm = { supplierId: string; productId: string; warehouseId: string; locationId: string; quantity: string; unitPrice: string; note: string };
export type TransactionLineForm = { productId: string; locationId: string; quantity: number; unitPrice: number };
export type ReportDashboard = { totalProducts: number; totalWarehouses: number; totalStock: number; lowStockCount: number; inboundCount: number; outboundCount: number; totalTransactions: number; totalInventoryValue: number; generatedAt: string };
export type InventoryValue = { productId: string; sku?: string; productName: string; warehouseCode: string; quantity: number; costPrice: number; totalValue: number };
export type LowStockReport = { productId: string; sku: string; productName: string; warehouseCode: string; locationCode?: string | null; quantity: number; minQuantity: number; shortage: number };
export type InoutChartPoint = { date: string; inboundQuantity: number; outboundQuantity: number; inboundValue?: number; outboundValue?: number };
export type StockMovement = { id: string; productId: string; warehouseId: string; warehouseCode?: string; locationId?: string | null; locationCode?: string | null; movementType: 'INBOUND' | 'OUTBOUND' | 'ADJUSTMENT'; quantityDelta: number; quantityAfter: number; referenceType?: string | null; note?: string | null; createdAt: string };
export type Toast = { id: number; type: 'success' | 'error' | 'info'; message: string };
export type ConfirmDialog = { title: string; message: string; actionLabel: string; danger?: boolean; onConfirm: () => Promise<void> | void };
export type ViewKey = 'overview' | 'products' | 'categories' | 'warehouses' | 'locations' | 'inventory' | 'suppliers' | 'inbound' | 'outbound' | 'transactions' | 'reports' | 'users';
export type FormModalKey = 'warehouse' | 'location' | 'stock' | 'transfer' | 'supplier' | 'inbound' | 'outbound' | 'category' | 'password';
export type ProductFormProps = { form: ProductForm; categories: Category[]; warehouses: Warehouse[]; allLocations: Location[]; suppliers: Supplier[]; saving: boolean; editingProductId: string | null; formError?: string; onChange: (form: ProductForm) => void; onImageChange: (file?: File) => void; onImageFileName?: string; onPreviewImage: (src: string, alt: string) => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void };
export type CurrencyInputProps = { value: string; onChange: (value: string) => void; placeholder?: string; required?: boolean; disabled?: boolean };
